/**
 * Bangladesh Districts and Thanas (Upazilas) Data
 * Complete list for address dropdowns
 */

export interface District {
  value: string;
  label: string;
}

export interface Thana {
  value: string;
  label: string;
}

// All 64 districts of Bangladesh
export const BANGLADESH_DISTRICTS: District[] = [
  { value: 'BAGERHAT', label: 'Bagerhat' },
  { value: 'BANDARBAN', label: 'Bandarban' },
  { value: 'BARGUNA', label: 'Barguna' },
  { value: 'BARISHAL', label: 'Barishal' },
  { value: 'BHOLA', label: 'Bhola' },
  { value: 'BOGURA', label: 'Bogura' },
  { value: 'BRAHMANBARIA', label: 'Brahmanbaria' },
  { value: 'CHANDPUR', label: 'Chandpur' },
  { value: 'CHAPAINAWABGANJ', label: 'Chapainawabganj' },
  { value: 'CHATTOGRAM', label: 'Chattogram' },
  { value: 'CHUADANGA', label: 'Chuadanga' },
  { value: 'COMILLA', label: 'Comilla' },
  { value: 'COXS_BAZAR', label: "Cox's Bazar" },
  { value: 'DHAKA', label: 'Dhaka' },
  { value: 'DINAJPUR', label: 'Dinajpur' },
  { value: 'FARIDPUR', label: 'Faridpur' },
  { value: 'FENI', label: 'Feni' },
  { value: 'GAIBANDHA', label: 'Gaibandha' },
  { value: 'GAZIPUR', label: 'Gazipur' },
  { value: 'GOPALGANJ', label: 'Gopalganj' },
  { value: 'HABIGANJ', label: 'Habiganj' },
  { value: 'JAMALPUR', label: 'Jamalpur' },
  { value: 'JASHORE', label: 'Jashore' },
  { value: 'JHALOKATI', label: 'Jhalokati' },
  { value: 'JHENAIDAH', label: 'Jhenaidah' },
  { value: 'JOYPURHAT', label: 'Joypurhat' },
  { value: 'KHAGRACHARI', label: 'Khagrachari' },
  { value: 'KHULNA', label: 'Khulna' },
  { value: 'KISHOREGANJ', label: 'Kishoreganj' },
  { value: 'KURIGRAM', label: 'Kurigram' },
  { value: 'KUSHTIA', label: 'Kushtia' },
  { value: 'LAKSHMIPUR', label: 'Lakshmipur' },
  { value: 'LALMONIRHAT', label: 'Lalmonirhat' },
  { value: 'MADARIPUR', label: 'Madaripur' },
  { value: 'MAGURA', label: 'Magura' },
  { value: 'MANIKGANJ', label: 'Manikganj' },
  { value: 'MEHERPUR', label: 'Meherpur' },
  { value: 'MOULVIBAZAR', label: 'Moulvibazar' },
  { value: 'MUNSHIGANJ', label: 'Munshiganj' },
  { value: 'MYMENSINGH', label: 'Mymensingh' },
  { value: 'NAOGAON', label: 'Naogaon' },
  { value: 'NARAIL', label: 'Narail' },
  { value: 'NARAYANGANJ', label: 'Narayanganj' },
  { value: 'NARSINGDI', label: 'Narsingdi' },
  { value: 'NATORE', label: 'Natore' },
  { value: 'NAWABGANJ', label: 'Nawabganj' },
  { value: 'NETROKONA', label: 'Netrokona' },
  { value: 'NILPHAMARI', label: 'Nilphamari' },
  { value: 'NOAKHALI', label: 'Noakhali' },
  { value: 'PABNA', label: 'Pabna' },
  { value: 'PANCHAGARH', label: 'Panchagarh' },
  { value: 'PATUAKHALI', label: 'Patuakhali' },
  { value: 'PIROJPUR', label: 'Pirojpur' },
  { value: 'RAJBARI', label: 'Rajbari' },
  { value: 'RAJSHAHI', label: 'Rajshahi' },
  { value: 'RANGAMATI', label: 'Rangamati' },
  { value: 'RANGPUR', label: 'Rangpur' },
  { value: 'SATKHIRA', label: 'Satkhira' },
  { value: 'SHARIATPUR', label: 'Shariatpur' },
  { value: 'SHERPUR', label: 'Sherpur' },
  { value: 'SIRAJGANJ', label: 'Sirajganj' },
  { value: 'SUNAMGANJ', label: 'Sunamganj' },
  { value: 'SYLHET', label: 'Sylhet' },
  { value: 'TANGAIL', label: 'Tangail' },
  { value: 'THAKURGAON', label: 'Thakurgaon' },
];

// Thanas/Upazilas by District
export const THANAS_BY_DISTRICT: Record<string, Thana[]> = {
  DHAKA: [
    { value: 'ADABOR', label: 'Adabor' },
    { value: 'BADDA', label: 'Badda' },
    { value: 'BANANI', label: 'Banani' },
    { value: 'BANGSHAL', label: 'Bangshal' },
    { value: 'BIMANBANDAR', label: 'Bimanbandar' },
    { value: 'CANTONMENT', label: 'Cantonment' },
    { value: 'CHAWKBAZAR', label: 'Chawkbazar' },
    { value: 'DARUS_SALAM', label: 'Darus Salam' },
    { value: 'DEMRA', label: 'Demra' },
    { value: 'DHANMONDI', label: 'Dhanmondi' },
    { value: 'GENDARIA', label: 'Gendaria' },
    { value: 'GULSHAN', label: 'Gulshan' },
    { value: 'HAZARIBAGH', label: 'Hazaribagh' },
    { value: 'JATRABARI', label: 'Jatrabari' },
    { value: 'KADAMTALI', label: 'Kadamtali' },
    { value: 'KAFRUL', label: 'Kafrul' },
    { value: 'KALABAGAN', label: 'Kalabagan' },
    { value: 'KAMRANGIRCHAR', label: 'Kamrangirchar' },
    { value: 'KHILGAON', label: 'Khilgaon' },
    { value: 'KHILKHET', label: 'Khilkhet' },
    { value: 'KOTWALI', label: 'Kotwali' },
    { value: 'LALBAGH', label: 'Lalbagh' },
    { value: 'MIRPUR', label: 'Mirpur' },
    { value: 'MOHAMMADPUR', label: 'Mohammadpur' },
    { value: 'MOTIJHEEL', label: 'Motijheel' },
    { value: 'NEW_MARKET', label: 'New Market' },
    { value: 'PALLABI', label: 'Pallabi' },
    { value: 'PALTAN', label: 'Paltan' },
    { value: 'RAMNA', label: 'Ramna' },
    { value: 'RAMPURA', label: 'Rampura' },
    { value: 'SABUJBAGH', label: 'Sabujbagh' },
    { value: 'SHAH_ALI', label: 'Shah Ali' },
    { value: 'SHAHBAGH', label: 'Shahbagh' },
    { value: 'SHER_E_BANGLA_NAGAR', label: 'Sher-e-Bangla Nagar' },
    { value: 'SHYAMPUR', label: 'Shyampur' },
    { value: 'SUTRAPUR', label: 'Sutrapur' },
    { value: 'TEJGAON', label: 'Tejgaon' },
    { value: 'TURAG', label: 'Turag' },
    { value: 'UTTARA', label: 'Uttara' },
    { value: 'UTTARA_EAST', label: 'Uttara East' },
    { value: 'UTTARA_WEST', label: 'Uttara West' },
    { value: 'VATARA', label: 'Vatara' },
    { value: 'WARI', label: 'Wari' },
  ],
  CHATTOGRAM: [
    { value: 'ANWARA', label: 'Anwara' },
    { value: 'BANSHKHALI', label: 'Banshkhali' },
    { value: 'BOALKHALI', label: 'Boalkhali' },
    { value: 'CHANDANAISH', label: 'Chandanaish' },
    { value: 'FATIKCHHARI', label: 'Fatikchhari' },
    { value: 'HATHAZARI', label: 'Hathazari' },
    { value: 'LOHAGARA', label: 'Lohagara' },
    { value: 'MIRSHARAI', label: 'Mirsharai' },
    { value: 'PATIYA', label: 'Patiya' },
    { value: 'RANGUNIA', label: 'Rangunia' },
    { value: 'RAOZAN', label: 'Raozan' },
    { value: 'SANDWIP', label: 'Sandwip' },
    { value: 'SATKANIA', label: 'Satkania' },
    { value: 'SITAKUNDA', label: 'Sitakunda' },
    { value: 'CTGCITY', label: 'Chattogram City' },
  ],
  GAZIPUR: [
    { value: 'GAZIPUR_SADAR', label: 'Gazipur Sadar' },
    { value: 'KALIAKAIR', label: 'Kaliakair' },
    { value: 'KALIGANJ', label: 'Kaliganj' },
    { value: 'KAPASIA', label: 'Kapasia' },
    { value: 'SREEPUR', label: 'Sreepur' },
  ],
  NARAYANGANJ: [
    { value: 'ARAIHAZAR', label: 'Araihazar' },
    { value: 'BANDAR', label: 'Bandar' },
    { value: 'NARAYANGANJ_SADAR', label: 'Narayanganj Sadar' },
    { value: 'RUPGANJ', label: 'Rupganj' },
    { value: 'SONARGAON', label: 'Sonargaon' },
  ],
  SYLHET: [
    { value: 'BALAGANJ', label: 'Balaganj' },
    { value: 'BEANIBAZAR', label: 'Beanibazar' },
    { value: 'BISHWANATH', label: 'Bishwanath' },
    { value: 'COMPANIGANJ', label: 'Companiganj' },
    { value: 'DAKSHIN_SURMA', label: 'Dakshin Surma' },
    { value: 'FENCHUGANJ', label: 'Fenchuganj' },
    { value: 'GOLAPGANJ', label: 'Golapganj' },
    { value: 'GOWAINGHAT', label: 'Gowainghat' },
    { value: 'JAINTIAPUR', label: 'Jaintiapur' },
    { value: 'KANAIGHAT', label: 'Kanaighat' },
    { value: 'OSMANINAGAR', label: 'Osmaninagar' },
    { value: 'SYLHET_SADAR', label: 'Sylhet Sadar' },
    { value: 'ZAKIGANJ', label: 'Zakiganj' },
  ],
  RAJSHAHI: [
    { value: 'BAGHA', label: 'Bagha' },
    { value: 'BAGMARA', label: 'Bagmara' },
    { value: 'CHARGHAT', label: 'Charghat' },
    { value: 'DURGAPUR', label: 'Durgapur' },
    { value: 'GODAGARI', label: 'Godagari' },
    { value: 'MOHANPUR', label: 'Mohanpur' },
    { value: 'PABA', label: 'Paba' },
    { value: 'PUTHIA', label: 'Puthia' },
    { value: 'RAJSHAHI_CITY', label: 'Rajshahi City' },
    { value: 'TANORE', label: 'Tanore' },
  ],
  KHULNA: [
    { value: 'BATIAGHATA', label: 'Batiaghata' },
    { value: 'DACOPE', label: 'Dacope' },
    { value: 'DIGHALIA', label: 'Dighalia' },
    { value: 'DUMURIA', label: 'Dumuria' },
    { value: 'KOYRA', label: 'Koyra' },
    { value: 'PAIKGACHA', label: 'Paikgacha' },
    { value: 'PHULTALA', label: 'Phultala' },
    { value: 'RUPSA', label: 'Rupsa' },
    { value: 'TEROKHADA', label: 'Terokhada' },
    { value: 'KHULNA_CITY', label: 'Khulna City' },
  ],
  BARISHAL: [
    { value: 'AGAILJHARA', label: 'Agailjhara' },
    { value: 'BABUGANJ', label: 'Babuganj' },
    { value: 'BAKERGANJ', label: 'Bakerganj' },
    { value: 'BANARIPARA', label: 'Banaripara' },
    { value: 'BARISHAL_SADAR', label: 'Barishal Sadar' },
    { value: 'GOURNADI', label: 'Gournadi' },
    { value: 'HIZLA', label: 'Hizla' },
    { value: 'MEHENDIGANJ', label: 'Mehendiganj' },
    { value: 'MULADI', label: 'Muladi' },
    { value: 'WAZIRPUR', label: 'Wazirpur' },
  ],
  RANGPUR: [
    { value: 'BADARGANJ', label: 'Badarganj' },
    { value: 'GANGACHARA', label: 'Gangachara' },
    { value: 'KAUNIA', label: 'Kaunia' },
    { value: 'MITHAPUKUR', label: 'Mithapukur' },
    { value: 'PIRGACHA', label: 'Pirgacha' },
    { value: 'PIRGANJ', label: 'Pirganj' },
    { value: 'RANGPUR_SADAR', label: 'Rangpur Sadar' },
    { value: 'TARAGANJ', label: 'Taraganj' },
  ],
  MYMENSINGH: [
    { value: 'BHALUKA', label: 'Bhaluka' },
    { value: 'DHOBAURA', label: 'Dhobaura' },
    { value: 'FULBARIA', label: 'Fulbaria' },
    { value: 'GAFFARGAON', label: 'Gaffargaon' },
    { value: 'GAURIPUR', label: 'Gauripur' },
    { value: 'HALUAGHAT', label: 'Haluaghat' },
    { value: 'ISHWARGANJ', label: 'Ishwarganj' },
    { value: 'MUKTAGACHA', label: 'Muktagacha' },
    { value: 'MYMENSINGH_SADAR', label: 'Mymensingh Sadar' },
    { value: 'NANDAIL', label: 'Nandail' },
    { value: 'PHULPUR', label: 'Phulpur' },
    { value: 'TRISHAL', label: 'Trishal' },
  ],
  COMILLA: [
    { value: 'BARURA', label: 'Barura' },
    { value: 'BRAHMANPARA', label: 'Brahmanpara' },
    { value: 'BURICHANG', label: 'Burichang' },
    { value: 'CHANDINA', label: 'Chandina' },
    { value: 'CHAUDDAGRAM', label: 'Chauddagram' },
    { value: 'COMILLA_SADAR', label: 'Comilla Sadar' },
    { value: 'DAUDKANDI', label: 'Daudkandi' },
    { value: 'DEBIDWAR', label: 'Debidwar' },
    { value: 'HOMNA', label: 'Homna' },
    { value: 'LAKSAM', label: 'Laksam' },
    { value: 'MEGHNA', label: 'Meghna' },
    { value: 'MURADNAGAR', label: 'Muradnagar' },
    { value: 'NANGALKOT', label: 'Nangalkot' },
    { value: 'SADAR_DAKSHIN', label: 'Sadar Dakshin' },
    { value: 'TITAS', label: 'Titas' },
  ],
};

// Get thanas for a specific district
export function getThanasByDistrict(district: string): Thana[] {
  return THANAS_BY_DISTRICT[district] || [{ value: 'OTHER', label: 'Other' }];
}

// Format date as DD-MON-YYYY (e.g., 16-JAN-2004)
export function formatDateDDMONYYYY(date: Date | string | undefined): string {
  if (!date) return '';
  
  const d = typeof date === 'string' ? new Date(date) : date;
  if (isNaN(d.getTime())) return '';
  
  const months = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
  const day = d.getDate().toString().padStart(2, '0');
  const month = months[d.getMonth()];
  const year = d.getFullYear();
  
  return `${day}-${month}-${year}`;
}
